using Microsoft.EntityFrameworkCore.Migrations;

namespace AptechStore.DataAccess.Migrations
{
    public partial class InsertDB : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"SET IDENTITY_INSERT [dbo].[Categories] ON 
                                    INSERT [dbo].[Categories] ([Id], [Name]) VALUES (1, N'Memoir')
                                    INSERT [dbo].[Categories] ([Id], [Name]) VALUES (2, N'Fiction')
                                    INSERT [dbo].[Categories] ([Id], [Name]) VALUES (3, N'Film')
                                    SET IDENTITY_INSERT [dbo].[Categories] OFF

                                    SET IDENTITY_INSERT [dbo].[Products] ON 
                                    INSERT [dbo].[Products] ([Id], [Title], [Description], [Price], [Author], [ImageUrl], [Quantity], [CategoryId]) VALUES (1, N'A Promised Land', N'<p style=''box - sizing: border - box; color: #333232; margin: 0px 0px 19.4444px; font-family: ''Avenir Next'', sans-serif; font-size: 15px; background-color: #ffffff;''><span style=''box-sizing: border-box; font-weight: bold;''>A riveting, deeply personal account of history in the making&mdash;from the president who inspired us to believe in the power of democracy</span></p>
                                    <p style = ''box-sizing: border-box; color: #333232; margin: 0px; font-family: ''Avenir Next'', sans-serif; font-size: 15px; background-color: #ffffff;'' >< br style = ''box-sizing: border-box;'' /> In the stirring, highly anticipated first volume of his presidential memoirs, Barack Obama tells the story of his improbable odyssey from young man searching for his identity to leader of the free world, describing in strikingly personal detail both his political education and the landmark moments of the first term of his historic presidency & mdash; a time of dramatic transformation and turmoil.</ p > ', 55, N'BARACK OBAMA', N'\images\products\b0fa1c30-d596-4ed6-b4ea-2137081e2fb3.jpg', 10, 1)
                                    INSERT[dbo].[Products]([Id], [Title], [Description], [Price], [Author], [ImageUrl], [Quantity], [CategoryId]) VALUES(2, N'Field Notes', N'<p style=''box-sizing: border-box; color: #333232; margin: 0px 0px 19.4444px; font-family: ''Avenir Next'', sans-serif; font-size: 15px; background-color: #ffffff;''><span style=''box-sizing: border-box; font-weight: bold;''>When Julia Zarankin saw her first red-winged blackbird at the age of thirty-five, she didn&rsquo;t expect that it would change her life. Recently divorced and auditioning hobbies during a stressful career transition, she stumbled on birdwatching, initially out of curiosity for the strange breed of humans who wear multi-pocketed vests, carry spotting scopes and discuss the finer points of optics with disturbing fervour. What she never could have predicted was that she would become one of them. Not only would she come to identify proudly as a birder, but birding would ultimately lead her to find love, uncover a new language and lay down her roots.</span></p>
                                    < p style = ''box-sizing: border-box; color: #333232; margin: 0px 0px 19.4444px; font-family: ''Avenir Next'', sans-serif; font-size: 15px; background-color: #ffffff;'' >< em style = ''box-sizing: border-box;'' > Field Notes from an Unintentional Birder </ em > &nbsp; tells the story of finding meaning in midlife through birds.The book follows the peregrinations of a narrator who learns more from birds than she ever anticipated, as she begins to realize that she herself is a migratory species: born in the former Soviet Union, growing up in Vancouver and Toronto, studying and working in the United States and living in Paris.Coming from a Russian immigrant family of concert pianists who believed that the outdoors were for &ldquo; other people, &rdquo; Julia Zarankin recounts the challenges and joys of unexpectedly discovering one & rsquo; s wild side and finding one&rsquo; s tribe in the unlikeliest of places.</ p > ', 25, N'JULIA ZARANKIN(CA)', N'\images\products\cbc7d271-e4a9-4f6c-8bea-48924b8a4f8f.jpg', 25, 1)
                                    INSERT[dbo].[Products]([Id], [Title], [Description], [Price], [Author], [ImageUrl], [Quantity], [CategoryId]) VALUES(3, N'Joe Biden', N'<p style=''box-sizing: border-box; color: #333232; margin: 0px 0px 19.4444px; font-family: ''Avenir Next'', sans-serif; font-size: 15px; background-color: #ffffff;''><span style=''box-sizing: border-box; font-weight: bold;''>A concise, brilliant, and trenchant examination of Democratic Nominee Joseph R. Biden Jr.&rsquo;s lifelong quest for the presidency by National Book Award winner Evan Osnos, adapted from nearly a decade of his reporting for&nbsp;<em style=''box-sizing: border-box;''>The New Yorker</em>.</span></p>
                                    < p style = ''box-sizing: border-box; color: #333232; margin: 0px; font-family: ''Avenir Next'', sans-serif; font-size: 15px; background-color: #ffffff;'' >< br style = ''box-sizing: border-box;'' /> Former vice president Joseph R.Biden Jr.has been called both the luckiest man and the unluckiest & mdash; fortunate to have sustained a fifty-year political career that reached the White House, but also marked by deep personal losses and disappointments that he has suffered.</ p > ', 32, N'EVAN OSNOS', N'\images\products\7c35c41a-0228-4ce9-a7ae-d26e01fec3a4.jpg', 20, 1)
                                    INSERT[dbo].[Products]([Id], [Title], [Description], [Price], [Author], [ImageUrl], [Quantity], [CategoryId]) VALUES(4, N'Vesper Flights', N'<p><span style=''box-sizing: border-box; font-weight: bold; color: #333232; font-family: ''Avenir Next'', sans-serif; font-size: 15px; background-color: #ffffff;''>From the bestselling author of&nbsp;<em style=''box-sizing: border-box;''>H is for Hawk</em>, a brilliant and insightful work about our relationship to the natural world</span><br style=''box-sizing: border-box; color: #333232; font-family: ''Avenir Next'', sans-serif; font-size: 15px; background-color: #ffffff;'' /><br style=''box-sizing: border-box; color: #333232; font-family: ''Avenir Next'', sans-serif; font-size: 15px; background-color: #ffffff;'' /><span style=''color: #333232; font-family: ''Avenir Next'', sans-serif; font-size: 15px; background-color: #ffffff;''>Our world is a fascinating place, teeming not only with natural wonders that defy description, but complex interactions that create layers of meaning. Helen Macdonald is gifted with a special lens that seems to peer right through it all, and she shares her insights--at times startling, nostalgic, weighty, or simply entertaining--in this masterful collection of essays.</span></p>', 30, N'HELEN MACDONALD', N'\images\products\0082addd-a191-4efd-9f48-c4c629ee3b59.jpg', 22, 1)
                                    INSERT[dbo].[Products]([Id], [Title], [Description], [Price], [Author], [ImageUrl], [Quantity], [CategoryId]) VALUES(5, N'Shuggie Bain', N'<h2 style=''box-sizing: border-box; margin: 0px 0px 27.5px; font-family: ''Avenir Next Rounded'', sans-serif; font-weight: 400; line-height: 1.2; overflow-wrap: break-word; font-size: 1.26667em; text-transform: uppercase; letter-spacing: 0.1em; color: #333232; background-color: #ffffff;''>NEW IN PAPERBACK</h2>
                                    < p style = ''box-sizing: border-box; color: #333232; margin: 0px 0px 19.4444px; font-family: ''Avenir Next'', sans-serif; font-size: 15px; background-color: #ffffff;'' > SHORTLISTED FOR THE BOOKER PRIZE </ p >
                                    < p style = ''box-sizing: border-box; color: #333232; margin: 0px 0px 19.4444px; font-family: ''Avenir Next'', sans-serif; font-size: 15px; background-color: #ffffff;'' >< em style = ''box-sizing: border-box;'' >Shuggie Bain </ em > &nbsp;is the unforgettable story of young Hugh &ldquo; Shuggie & rdquo; Bain, a sweet and lonely boy who spends his 1980s childhood in run - down public housing in Glasgow, Scotland.Thatcher&rsquo;s policies have put husbands and sons out of work, and the city&rsquo;s notorious drugs epidemic is waiting in the wings.</p>', 26, N'DOUGLAS STUART', N'\images\products\955f7dac-7796-4d0c-a7d0-f6c645144066.jpg', 15, 2)
                                    INSERT[dbo].[Products] ([Id], [Title], [Description], [Price], [Author], [ImageUrl], [Quantity], [CategoryId]) VALUES (6, N'The Lying Life of Adults', N'<p style=''box-sizing: border-box; color: #333232; margin: 0px 0px 19.4444px; font-family: ''Avenir Next'', sans-serif; font-size: 15px; background-color: #ffffff;''><span style=''box-sizing: border-box; font-weight: bold;''>A&nbsp;powerful new novel set in a divided Naples by the&nbsp;<em style=''box-sizing: border-box;''>New York Times</em>&nbsp;best-selling author of&nbsp;<em style=''box-sizing: border-box;''>My Brilliant Friend</em>&nbsp;and&nbsp;<em style=''box-sizing: border-box;''>The Lost Daughter</em>.</span></p>
                                    <p style = ''box-sizing: border-box; color: #333232; margin: 0px 0px 19.4444px; font-family: ''Avenir Next'', sans-serif; font-size: 15px; background-color: #ffffff;'' >< span style= ''box-sizing: border-box; font-weight: bold;''> Soon to be a NETFLIX Original Series</span></p>
                                    <p style = ''box-sizing: border-box; color: #333232; margin: 0px 0px 19.4444px; font-family: ''Avenir Next'', sans-serif; font-size: 15px; background-color: #ffffff;'' > Giovanna & rsquo; s pretty face is changing, turning ugly, at least so her father thinks.Giovanna, he says, looks more like her Aunt Vittoria every day.But can it be true? Is she really changing? Is she turning into her Aunt Vittoria, a woman she hardly knows but whom her mother and father clearly despise? Surely there is a mirror somewhere in which she can see herself as she truly is.</p>', 39, N'ELENA FERRANTE', N'\images\products\49a441f9-e2e3-4d67-89d5-e99ba1edc19c.jpg', 20, 2)
                                    INSERT[dbo].[Products]
                                            ([Id], [Title], [Description], [Price], [Author], [ImageUrl], [Quantity], [CategoryId]) VALUES(7, N'Earthlings', N'<p style=''box-sizing: border-box; color: #333232; margin: 0px 0px 19.4444px; font-family: ''Avenir Next'', sans-serif; font-size: 15px; background-color: #ffffff;''><span style=''box-sizing: border-box; font-weight: bold;''>As a child, Natsuki doesn&rsquo;t fit into her family. Her parents favor her sister, and her best friend is a plush toy hedgehog named Piyyut who has explained to her that he has come from the planet Popinpobopia on a special quest to help her save the Earth.</span></p>
                                    <p style = ''box-sizing: border-box; color: #333232; margin: 0px; font-family: ''Avenir Next'', sans-serif; font-size: 15px; background-color: #ffffff;'' > Each summer, Natsuki counts down the days until her family drives into the mountains of Nagano to visit her grandparents in their wooden house in the forest, a place that couldn&rsquo; t be more different from her grey commuter town.One summer, her cousin Yuu confides to Natsuki that he is an extraterrestrial and that every night he searches the sky for the spaceship that might take him</p>', 37, N'SAYAKA MURATA', N'\images\products\fdc25f1c-f8ba-4f55-8764-d0a6781714c3.jpg', 22, 2)
                                    INSERT[dbo].[Products] ([Id], [Title], [Description], [Price], [Author], [ImageUrl], [Quantity], [CategoryId]) VALUES (8, N'Girls Against God', N'<p><span style=''box-sizing: border-box; font-weight: bold; color: #333232; font-family: ''Avenir Next'', sans-serif; font-size: 15px; background-color: #ffffff;''>A genre-warping, time-travelling horror novel-slash-feminist manifesto for fans of&nbsp;Clarice Lispector and&nbsp;Jeanette Winterson.</span><br style=''box-sizing: border-box; color: #333232; font-family: ''Avenir Next'', sans-serif; font-size: 15px; background-color: #ffffff;'' /><br style=''box-sizing: border-box; color: #333232; font-family: ''Avenir Next'', sans-serif; font-size: 15px; background-color: #ffffff;'' /><span style=''color: #333232; font-family: ''Avenir Next'', sans-serif; font-size: 15px; background-color: #ffffff;''>Welcome to 1990s Norway. White picket fences run in neat rows and Christian conservatism runs deep. But as the Artist considers her work, things start stirring themselves up. In a corner of Oslo a coven of witches begin cooking up some curses. A time-travelling Edvard Munch arrives in town to join a death metal band, closely pursued by the teenaged subject of his painting Puberty, who has murder on her mind. Meanwhile, out deep in the forest, a group of school girls get very lost and things get very strange. And awful things happen in aspic.</span></p>', 26, N'JENNY HVAL', N'\images\products\e7ce4632-3bce-4221-8549-1e4576897e47.jpg', 24, 2)
                                    INSERT[dbo].[Products]
                                            ([Id], [Title], [Description], [Price], [Author], [ImageUrl], [Quantity], [CategoryId]) VALUES(9, N'Shit, Actually', N'<p style=''box-sizing: border-box; color: #333232; margin: 0px 0px 19.4444px; font-family: ''Avenir Next'', sans-serif; font-size: 15px; background-color: #ffffff;''><span style=''box-sizing: border-box; font-weight: bold;''>This book is maybe the only good thing to come out of 2020. I was laughing so loud that my dog kept coming to check on me. - RA</span></p>
                                    <div style = ''box-sizing: border-box; color: #333232; font-family: ''Avenir Next'', sans-serif; font-size: 15px; background-color: #ffffff;'' >< span style= ''box-sizing: border-box; font-weight: bold;''> &nbsp;</span></div>
                                    <div style = ''box-sizing: border-box; color: #333232; font-family: ''Avenir Next'', sans-serif; font-size: 15px; background-color: #ffffff;''>< em style=''box-sizing: border-box;''>New York Times</em>&nbsp;opinion writer and bestselling author Lindy West was once the in-house movie critic for Seattle''s alternative newsweekly&nbsp;<em style = ''box-sizing: border-box;'' > The Stranger</em>, where she covered film with brutal honesty and giddy irreverence.In&nbsp;<em style = ''box-sizing: border-box;'' > Shit, Actually,</em>&nbsp;Lindy returns to those roots, re-examining beloved and iconic movies from the past 40 years with an eye toward the big questions of our time: Is&nbsp;<em style = ''box-sizing: border-box;'' > Twilight & nbsp;</em>the horniest movie in history? Why do the zebras in&nbsp;<em style = ''box-sizing: border-box;'' > The Lion King&nbsp;</em>trust Mufasa-WHO IS A LION-to look out for their best interests? Why did anyone bother making any more movies after&nbsp;<em style = ''box-sizing: border-box;'' > The Fugitive</em>&nbsp;achieved perfection? And, my god, why don''t any of the women in&nbsp;<em style = ''box-sizing: border-box;'' > Love, Actually&nbsp;</em>ever fucking talk?!?!</div>', 34, N'LINDY WEST', N'\images\products\4847e4c7-f7e1-4446-afe3-361400dcc577.jpg', 15, 3)
                                    SET IDENTITY_INSERT[dbo].[Products] OFF");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
